### ISSUE TITLE
Inconsistent raw data in Row returned from BuffReaderFixedParser vs BuffReaderDelimParser

### ISSUE THREAD

**Issue by icemanltd** [Appendium/flatpack#18]
If a user chooses to keep a copy of the raw data in the returned row, both BuffReaderDelimParser and BuffReaderFixedParser add the parsed line to the row that is returned. There is a difference though in that if the line is longer than the metadata indicates, the line is first truncated to the specified length.

In BuffReaderDelimParser, the line is first parsed to columns, then if there are too many columns the extra columns are removed from the array but the orignal line is left unchanged and set in the returned Row.

Would it be possible to return the original line in it's entirety in both cases? I realize that this might create an issue with users already relying on the current behavior. Perhaps it would be possible for the Row to (optionally) have both the original, unmodified line as well as the substring of the line that was used to create the row?

**Comment by benoitx** [comment]
I'd say that it is a bug, I'd have expected the Row to be the full one and not truncated for the FixedParser.
Do you have a pull request with a test for this?
many thanks

**Comment by icemanltd** [comment]
I have made what I think are appropriate changes and added test cases to support both the delimited and fixed parsers.

I have committed and generated a pull request.

**Comment by benoitx** [comment]
hi

You seem to have cloned an old repo (ks-appendium) rather than
appendium/flatpack.

Any chance you could cancel the PR and redo this against master in
https://github.com/Appendium/flatpack ?

If not, I'll try manually...

Many thanks

Benoit

On 6 August 2015 at 05:51, icemanltd <notifications@github.com> wrote:

> I have made what I think are appropriate changes and added test cases to
> support both the delimited and fixed parsers.
>
> I have committed and generated a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Appendium/flatpack/issues/18#issuecomment-128238427>.
>



-- 
Follow us on Twitter @appendium <http://twitter.com/appendium> and
http://www.appendium.com
----

IMPORTANT NOTICE This communication contains information that is considered
confidential and may also be privileged . It is for the exclusive use of
the intended recipient(s). If you are not the intended recipient(s) please
note that any form of distribution, copying or use of this communication or
the information in it is strictly prohibited and may be unlawful. If you
have received this communication in error please return it to the sender
and delete the original.

**Comment by icemanltd** [comment]
I apologize, I see my mistake now. I will cancel those pull requests and do it over against the correct source.

**Comment by benoitx** [comment]
Any chance of adding a test case for these 2 scenarios?
Many thanks in advance.

**Comment by icemanltd** [comment]
Again, I apologize. I have not used Git before now. The tests were there but I guess they did not get added. I have added them and it appears the pull request was automatically updated? 

Date: Sun, 9 Aug 2015 06:09:13 -0700

**Comment by benoitx** [comment]
Merged the Pull Request fixing this issue
